In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [35]:
df_1 = pd.read_csv('../data/raw/startup_data.csv')
display(df_1)

,Unnamed: 0,state_code,latitude,longitude,zip_code,id,city,Unnamed: 6,name,labels,founded_at,closed_at,first_funding_at,last_funding_at,age_first_funding_year,age_last_funding_year,age_first_milestone_year,age_last_milestone_year,relationships,funding_rounds,funding_total_usd,milestones,state_code.1,is_CA,is_NY,is_MA,is_TX,is_otherstate,category_code,is_software,is_web,is_mobile,is_enterprise,is_advertising,is_gamesvideo,is_ecommerce,is_biotech,is_consulting,is_othercategory,object_id,has_VC,has_angel,has_roundA,has_roundB,has_roundC,has_roundD,avg_participants,is_top500,status
0,1005,CA,42.358880,-71.056820,92101,c:6669,San Diego,NaN,Bandsintown,1,1/1/2007,NaN,4/1/2009,1/1/2010,2.2493,3.0027,4.6685,6.7041,3,3,375000,3,CA,1,0,0,0,0,music,0,0,0,0,0,0,0,0,0,1,c:6669,0,1,0,0,0,0,1.0000,0,acquired
1,204,CA,37.238916,-121.973718,95032,c:16283,Los Gatos,NaN,TriCipher,1,1/1/2000,NaN,2/14/2005,12/28/2009,5.1260,9.9973,7.0055,7.0055,9,4,40100000,1,CA,1,0,0,0,0,enterprise,0,0,0,1,0,0,0,0,0,0,c:16283,1,0,0,1,1,1,4.7500,1,acquired
2,1001,CA,32.901049,-117.192656,92121,c:65620,San Diego,San Diego CA 92121,Plixi,1,3/18/2009,NaN,3/30/2010,3/30/2010,1.0329,1.0329,1.4575,2.2055,5,1,2600000,2,CA,1,0,0,0,0,web,0,1,0,0,0,0,0,0,0,0,c:65620,0,0,1,0,0,0,4.0000,1,acquired
3,738,CA,37.320309,-122.050040,95014,c:42668,Cupertino,Cupertino CA 95014,Solidcore Systems,1,1/1/2002,NaN,2/17/2005,4/25/2007,3.1315,5.3151,6.0027,6.0027,5,3,40000000,1,CA,1,0,0,0,0,software,1,0,0,0,0,0,0,0,0,0,c:42668,0,0,0,1,1,1,3.3333,1,acquired
4,1002,CA,37.779281,-122.419236,94105,c:65806,San Francisco,San Francisco CA 94105,Inhale Digital,0,8/1/2010,10/1/2012,8/1/2010,4/1/2012,0.0000,1.6685,0.0384,0.0384,2,2,1300000,1,CA,1,0,0,0,0,games_video,0,0,0,0,0,1,0,0,0,0,c:65806,1,1,0,0,0,0,1.0000,1,closed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
918,352,CA,37.740594,-122.376471,94107,c:21343,San Francisco,NaN,CoTweet,1,1/1/2009,NaN,7/9/2009,7/9/2009,0.5178,0.5178,0.5808,4.5260,9,1,1100000,2,CA,1,0,0,0,0,advertising,0,0,0,0,1,0,0,0,0,0,c:21343,0,0,1,0,0,0,6.0000,1,acquired
919,721,MA,42.504817,-71.195611,1803,c:41747,Burlington,Burlington MA 1803,Reef Point Systems,0,1/1/1998,6/25/2008,4/1/2005,3/23/2007,7.2521,9.2274,6.0027,6.0027,1,3,52000000,1,MA,0,0,1,0,0,security,0,0,0,0,0,0,0,0,0,1,c:41747,1,0,0,1,0,0,2.6667,1,closed
920,557,CA,37.408261,-122.015920,94089,c:31549,Sunnyvale,NaN,Paracor Medical,0,1/1/1999,6/17/2012,6/29/2007,6/29/2007,8.4959,8.4959,9.0055,9.0055,5,1,44000000,1,CA,1,0,0,0,0,biotech,0,0,0,0,0,0,0,1,0,0,c:31549,0,0,0,0,0,1,8.0000,1,closed
921,589,CA,37.556732,-122.288378,94404,c:33198,San Francisco,NaN,Causata,1,1/1/2009,NaN,10/5/2009,11/1/2011,0.7589,2.8329,0.7589,3.8356,12,2,15500000,2,CA,1,0,0,0,0,software,1,0,0,0,0,0,0,0,0,0,c:33198,0,0,1,1,0,0,1.0000,1,acquired
922,462,CA,37.386778,-121.966277,95054,c:26702,Santa Clara,Santa Clara CA 95054,Asempra Technologies,1,1/1/2003,NaN,2/13/2006,2/13/2006,3.1205,3.1205,4.0027,4.0027,4,1,20000000,1,CA,1,0,0,0,0,security,0,0,0,0,0,0,0,0,0,1,c:26702,0,0,0,1,0,0,3.0000,1,acquired

In [36]:
df_3 = pd.read_csv('../data/raw/New_Business_Density(Startups)_Dataset_2015_to_2020.csv')
display(df_3)

,Year,Country Name,Country Code,"New business density (new registrations per 1,000 people ages 15-64)",Research and development expenditure (% of GDP),Market capitalization of listed domestic companies (% of GDP),Individuals using the Internet (% of population),"School enrollment, tertiary (% gross)","Unemployment, total (% of total labor force) (modeled ILO estimate)",Political Stability and Absence of Violence/Terrorism: Estimate,"Foreign direct investment, net inflows (% of GDP)","Inflation, consumer prices (annual %)",Access to electricity (% of population),Mobile cellular subscriptions (per 100 people),Population density (people per sq. km of land area),Lending interest rate (%),"Labor force participation rate, total (% of total population ages 15+) (modeled ILO estimate)",Exports of goods and services (% of GDP),"Government expenditure on education, total (% of GDP)","Patent applications, residents","GNI per capita, Atlas method (current US$)",Imports of goods and services (% of GDP),Current health expenditure (% of GDP),Renewable energy consumption (% of total final energy consumption),Bank capital to assets ratio (%),High-technology exports (% of manufactured exports),"Birth rate, crude (per 1,000 people)","Intentional homicides (per 100,000 people)",Ratio of female to male labor force participation rate (%) (national estimate)
0,2020,Afghanistan,AFG,NaN,NaN,NaN,18.400000,10.858440,11.710,-2.702632,0.064389,NaN,97.700000,58.190214,59.752281,NaN,41.580,NaN,NaN,NaN,500.0,NaN,15.533614,17.58,NaN,NaN,36.051,6.594439,24.685817
1,2020,Albania,ALB,1.524836,NaN,NaN,72.237677,61.392578,13.067,0.088576,7.055092,1.620887,100.000000,91.350501,103.571131,6.120833,56.845,22.657790,3.342300,NaN,5270.0,37.171940,NaN,44.58,9.069008,0.285854,10.285,2.127772,NaN
2,2020,Algeria,DZA,NaN,NaN,NaN,63.949996,53.614029,12.248,-0.847814,0.784883,2.415131,99.718773,104.842178,18.243657,8.000000,39.349,17.469840,7.042397,163.0,3610.0,27.860671,6.321180,0.15,10.288545,NaN,22.431,1.505121,NaN
3,2020,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,1.091602,NaN,NaN,NaN,NaN,230.945000,NaN,NaN,59.497207,NaN,NaN,NaN,96.508380,NaN,0.51,NaN,NaN,12.700,NaN,NaN
4,2020,Andorra,AND,NaN,NaN,NaN,93.205649,15.098270,NaN,1.588572,NaN,NaN,100.000000,103.449163,165.319149,NaN,NaN,NaN,2.856163,3.0,NaN,NaN,9.051759,21.86,NaN,NaN,NaN,2.574003,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1297,2015,Virgin Islands (U.S.),VIR,NaN,NaN,NaN,54.839137,NaN,12.258,1.220002,NaN,NaN,100.000000,NaN,307.748571,NaN,58.651,41.632542,NaN,NaN,NaN,43.134043,NaN,5.14,NaN,NaN,13.200,NaN,NaN
1298,2015,West Bank and Gaza,PSE,NaN,NaN,23.898543,56.700000,46.583752,23.000,-2.154096,0.751036,1.431611,99.900000,77.961373,709.317608,6.782108,43.970,16.062380,4.663220,NaN,3670.0,54.718588,NaN,10.99,9.713170,0.961928,32.726,1.204117,25.416667
1299,2015,"Yemen, Rep.",YEM,NaN,NaN,NaN,24.085409,NaN,13.783,-2.668016,-0.036388,NaN,67.414886,52.678026,54.011677,NaN,37.018,18.321800,NaN,5.0,1110.0,40.846043,4.252857,1.96,NaN,4.829284,33.933,NaN,NaN
1300,2015,Zambia,ZMB,1.111697,NaN,NaN,8.800000,NaN,8.280,0.144710,7.447417,10.110593,31.100000,71.132209,21.856939,13.250000,58.893,37.138526,4.624330,20.0,1540.0,42.726891,4.435102,83.09,11.160385,7.627948,37.832,5.249803,NaN
1301,2015,Zimbabwe,ZWE,1.200407,NaN,NaN,22.742818,10.600870,5.282,-0.619207,1.999687,-2.430968,33.700000,90.126929,36.590247,8.541771,65.913,19.160176,NaN,9.0,1220.0,37.588635,7.449827,81.00,NaN,3.276828,33.960,NaN,NaN

In [37]:
df_4 = pd.read_csv('../data/raw/list_of_Unicorns_in_the_World.csv')
display(df_4)

,Unnamed: 0,Company,Valuation ($B),Date Joined,Country,City,Industry
0,0,ByteDance,$225,4/7/2017,China,Beijing,Media & Entertainment
1,1,SpaceX,$150,12/1/2012,United States,Hawthorne,Industrials
2,2,OpenAI,$80,7/22/2019,United States,San Francisco,Enterprise Tech
3,3,SHEIN,$66,7/3/2018,Singapore,Singapore City,Consumer & Retail
4,4,Stripe,$65,1/23/2014,United States,San Francisco,Financial Services
...,...,...,...,...,...,...,...
1228,1228,LeadSquared,$1,6/21/2022,India,Bengaluru,Enterprise Tech
1229,1229,FourKites,$1,6/21/2022,United States,Chicago,Enterprise Tech
1230,1230,VulcanForms,$1,7/5/2022,United States,Burlington,Industrials
1231,1231,SingleStore,$1,7/12/2022,United States,San Francisco,Enterprise Tech
1232,1232,Unstoppable Domains,$1,7/27/2022,United States,Las Vegas,Media & Entertainment

In [38]:
df_5 = pd.read_csv('../data/raw/big_startup_secsees_dataset.csv')
display(df_5)

,permalink,name,homepage_url,category_list,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,first_funding_at,last_funding_at
0,/organization/-fame,#fame,http://livfame.com,Media,10000000,operating,IND,16,Mumbai,Mumbai,1,NaN,2015-01-05,2015-01-05
1,/organization/-qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,700000,operating,USA,DE,DE - Other,Delaware City,2,2014-09-04,2014-03-01,2014-10-14
2,/organization/-the-one-of-them-inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,3406878,operating,NaN,NaN,NaN,NaN,1,NaN,2014-01-30,2014-01-30
3,/organization/0-6-com,0-6.com,http://www.0-6.com,Curated Web,2000000,operating,CHN,22,Beijing,Beijing,1,2007-01-01,2008-03-19,2008-03-19
4,/organization/004-technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,-,operating,USA,IL,"Springfield, Illinois",Champaign,1,2010-01-01,2014-07-24,2014-07-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66363,/organization/zznode-science-and-technology-co...,ZZNode Science and Technology,http://www.zznode.com,Enterprise Software,1587301,operating,CHN,22,Beijing,Beijing,1,NaN,2012-04-01,2012-04-01
66364,/organization/zzzzapp-com,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,114304,operating,HRV,15,Split,Split,4,2012-05-13,2011-11-01,2014-03-01
66365,/organization/Áeron,ÁERON,http://www.aeron.hu/,NaN,-,operating,NaN,NaN,NaN,NaN,1,2011-01-01,2014-08-01,2014-08-01
66366,/organization/Ôasys-2,Ôasys,http://www.oasys.io/,Consumer Electronics|Internet of Things|Teleco...,18192,operating,USA,CA,SF Bay Area,San Francisco,1,2014-01-01,2015-01-01,2015-01-01
66367,/organization/İnovatiff-reklam-ve-tanıtım-hizm...,İnovatiff Reklam ve Tanıtım Hizmetleri Tic,http://inovatiff.com,Consumer Goods|E-Commerce|Internet,14851,operating,NaN,NaN,NaN,NaN,1,NaN,2013-10-01,2013-10-01

In [39]:
# Standardize column names to lowercase for consistency
df_1.columns = df_1.columns.str.lower()

# Drop unnecessary columns
df_1 = df_1.drop(columns=['unnamed: 0', 'unnamed: 6', 'labels', 'relationships', 'milestones', 'latitude', 'longitude'])

# Fill missing values in `closed_at` with 'operating' to indicate active startups
df_1['closed_at'] = df_1['closed_at'].fillna('operating')

# Impute missing values for `age_first_milestone_year` and `age_last_milestone_year` with the median
df_1['age_first_milestone_year'].fillna(df_1['age_first_milestone_year'].median(), inplace=True)
df_1['age_last_milestone_year'].fillna(df_1['age_last_milestone_year'].median(), inplace=True)

/var/folders/1p/3nvyb0qn4zbfkzm72nmsffqh0000gn/T/ipykernel_13055/4272531732.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_1['age_first_milestone_year'].fillna(df_1['age_first_milestone_year'].median(), inplace=True)
/var/folders/1p/3nvyb0qn4zbfkzm72nmsffqh0000gn/T/ipykernel_13055/4272531732.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_1['age_last_milestone_year'].fillna(df_1['age_last_milestone_year'].median(), inplace=True)

In [40]:
# Standardize column names to lowercase
df_3.columns = df_3.columns.str.lower()

# Drop columns with high NA counts or less relevance
df_3 = df_3.drop(columns=[
    'intentional homicides (per 100,000 people)',
    'birth rate, crude (per 1,000 people)',
    'high-technology exports (% of manufactured exports)',
    'bank capital to assets ratio (%)'
])

# Fill missing values for key columns with the median by country where possible
df_3['new business density (new registrations per 1,000 people ages 15-64)'] = \
    df_3.groupby('country name')['new business density (new registrations per 1,000 people ages 15-64)'] \
    .transform(lambda x: x.fillna(x.median()))

df_3['research and development expenditure (% of gdp)'] = \
    df_3.groupby('country name')['research and development expenditure (% of gdp)'] \
    .transform(lambda x: x.fillna(x.median()))

/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [41]:
# Standardize column names to lowercase
df_4.columns = df_4.columns.str.lower()

# Drop `unnamed: 0` and `city`, which are unnecessary
df_4 = df_4.drop(columns=['unnamed: 0', 'city'])

In [42]:
# Convert 'founded_at' to datetime format
df_5['founded_at'] = pd.to_datetime(df_5['founded_at'], errors='coerce')

# Impute missing founding dates with the median founding date within each country
df_5['founded_at'] = df_5.groupby('country_code')['founded_at'].transform(lambda x: x.fillna(x.median()))

# Drop rows with missing `country_code` if critical for merging or modeling
df_5.dropna(subset=['country_code'], inplace=True)

/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/jeanphilippeauguste/Documents/projects/startup-success-predictor/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [43]:
# Merge df_1 and df_5 on relevant startup identifiers (e.g., name or id)
merged_df = pd.merge(df_1, df_5, how='left', left_on='name', right_on='name', suffixes=('_df1', '_df5'))
merged_df

,state_code_df1,zip_code,id,city_df1,name,founded_at_df1,closed_at,first_funding_at_df1,last_funding_at_df1,age_first_funding_year,age_last_funding_year,age_first_milestone_year,age_last_milestone_year,funding_rounds_df1,funding_total_usd_df1,state_code.1,is_ca,is_ny,is_ma,is_tx,is_otherstate,category_code,is_software,is_web,is_mobile,is_enterprise,is_advertising,is_gamesvideo,is_ecommerce,is_biotech,is_consulting,is_othercategory,object_id,has_vc,has_angel,has_rounda,has_roundb,has_roundc,has_roundd,avg_participants,is_top500,status_df1,permalink,homepage_url,category_list,funding_total_usd_df5,status_df5,country_code,state_code_df5,region,city_df5,funding_rounds_df5,founded_at_df5,first_funding_at_df5,last_funding_at_df5
0,CA,92101,c:6669,San Diego,Bandsintown,1/1/2007,operating,4/1/2009,1/1/2010,2.2493,3.0027,4.6685,6.7041,3,375000,CA,1,0,0,0,0,music,0,0,0,0,0,0,0,0,0,1,c:6669,0,1,0,0,0,0,1.0000,0,acquired,/organization/bandsintown,http://www.bandsintown.com/home,Apps|Concerts|Ediscovery|Events|Facebook Appli...,375000,acquired,USA,CA,San Diego,San Diego,4.0,2007-01-01,2006-08-01,2010-01-01
1,CA,95032,c:16283,Los Gatos,TriCipher,1/1/2000,operating,2/14/2005,12/28/2009,5.1260,9.9973,7.0055,7.0055,4,40100000,CA,1,0,0,0,0,enterprise,0,0,0,1,0,0,0,0,0,0,c:16283,1,0,0,1,1,1,4.7500,1,acquired,/organization/tricipher,http://www.tricipher.com,Enterprise Software,40100000,acquired,USA,CA,SF Bay Area,Los Gatos,4.0,2000-01-01,2005-02-14,2009-12-28
2,CA,92121,c:65620,San Diego,Plixi,3/18/2009,operating,3/30/2010,3/30/2010,1.0329,1.0329,1.4575,2.2055,1,2600000,CA,1,0,0,0,0,web,0,1,0,0,0,0,0,0,0,0,c:65620,0,0,1,0,0,0,4.0000,1,acquired,/organization/plixi,http://plixi.com,Curated Web|Photography,2600000,acquired,USA,CA,San Diego,San Diego,1.0,2009-03-18,2010-03-30,2010-03-30
3,CA,95014,c:42668,Cupertino,Solidcore Systems,1/1/2002,operating,2/17/2005,4/25/2007,3.1315,5.3151,6.0027,6.0027,3,40000000,CA,1,0,0,0,0,software,1,0,0,0,0,0,0,0,0,0,c:42668,0,0,0,1,1,1,3.3333,1,acquired,/organization/solidcore-systems,http://www.solidcore.com,Software,60950000,acquired,USA,CA,SF Bay Area,Cupertino,5.0,2002-01-01,2003-11-21,2008-08-08
4,CA,94105,c:65806,San Francisco,Inhale Digital,8/1/2010,10/1/2012,8/1/2010,4/1/2012,0.0000,1.6685,0.0384,0.0384,2,1300000,CA,1,0,0,0,0,games_video,0,0,0,0,0,1,0,0,0,0,c:65806,1,1,0,0,0,0,1.0000,1,closed,/organization/inhale-digital,http://www.inhaledigital.com,Coupons|Facebook Applications|Flash Sales|Game...,1300000,closed,USA,CA,SF Bay Area,San Francisco,2.0,2010-08-01,2010-08-01,2012-04-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,CA,94107,c:21343,San Francisco,CoTweet,1/1/2009,operating,7/9/2009,7/9/2009,0.5178,0.5178,0.5808,4.5260,1,1100000,CA,1,0,0,0,0,advertising,0,0,0,0,1,0,0,0,0,0,c:21343,0,0,1,0,0,0,6.0000,1,acquired,/organization/cotweet,http://cotweet.com,Advertising|CRM|Twitter Applications,1100000,acquired,USA,CA,SF Bay Area,San Francisco,1.0,2009-01-01,2009-07-09,2009-07-09
924,MA,1803,c:41747,Burlington,Reef Point Systems,1/1/1998,6/25/2008,4/1/2005,3/23/2007,7.2521,9.2274,6.0027,6.0027,3,52000000,MA,0,0,1,0,0,security,0,0,0,0,0,0,0,0,0,1,c:41747,1,0,0,1,0,0,2.6667,1,closed,/organization/reef-point-systems,http://www.reefpoint.com,Security,52000000,closed,USA,MA,Boston,Burlington,3.0,1998-01-01,2005-04-01,2007-03-23
925,CA,94089,c:31549,Sunnyvale,Paracor Medical,1/1/1999,6/17/2012,6/29/2007,6/29/2007,8.4959,8.4959,9.0055,9.0055,1,44000000,CA,1,0,0,0,0,biotech,0,0,0,0,0,0,0,1,0,0,c:31549,0,0,0,0,0,1,8.0000,1,closed,/organization/paracor-medical,http://www.paracormedical.com,Health Care,44000000,closed,USA,CA,SF Bay Area,Sunnyvale,1.0,1999-01-01,2007-06-29,2007-06-29
926,CA,94404,c:33198,San Francisco,Causata,1/1/2009,operating,10/5/2009,11/1/2011,0.7589,2.8329,0.7589,3.8356,2,15500000,CA,1,0,0,0,0,software,1,0,0,0,0,0,0,0,0,0,c:33198,0,0,1,1,0,0,1.0000,1,acquired,/organization/causata,http://www.causata.com,Big Data|Predictive Analytics|Software,15500000,acquired,USA,CA,SF Bay Area,San Francisco,2.0,2009-01-01,2009-10-05,2011-11-01
927,CA,95054,c:26702,Santa Clara,Asempra Technologies,1/1/2003,operating,2/13/2006,2/13/2006,3.1205,3.1205,4.0027,4.0027,1,20000000,CA,1,0,0,0,0,security,0,0,0,0,0,0,0,0,0,1,c:26702,0,0,0,1,0,0,3.0000,1,acquired,/organization/asempra-technologies,NaN,Software,20000000,acquired,USA,CA,SF Bay Area,Santa Clara,1.0,2003-01-01,2006-02-13,2006-02-13

In [44]:
# Select relevant year for df_3 (e.g., latest available for consistent analysis)
df_3_latest = df_3[df_3['year'] == df_3['year'].max()]

# Merge country-level data with `merged_df`
merged_df = pd.merge(merged_df, df_3_latest, how='left', left_on='name', right_on='country code')
merged_df

,state_code_df1,zip_code,id,city_df1,name,founded_at_df1,closed_at,first_funding_at_df1,last_funding_at_df1,age_first_funding_year,age_last_funding_year,age_first_milestone_year,age_last_milestone_year,funding_rounds_df1,funding_total_usd_df1,state_code.1,is_ca,is_ny,is_ma,is_tx,is_otherstate,category_code,is_software,is_web,is_mobile,is_enterprise,is_advertising,is_gamesvideo,is_ecommerce,is_biotech,is_consulting,is_othercategory,object_id,has_vc,has_angel,has_rounda,has_roundb,has_roundc,has_roundd,avg_participants,is_top500,status_df1,permalink,homepage_url,category_list,funding_total_usd_df5,status_df5,country_code,state_code_df5,region,city_df5,funding_rounds_df5,founded_at_df5,first_funding_at_df5,last_funding_at_df5,year,country name,country code,"new business density (new registrations per 1,000 people ages 15-64)",research and development expenditure (% of gdp),market capitalization of listed domestic companies (% of gdp),individuals using the internet (% of population),"school enrollment, tertiary (% gross)","unemployment, total (% of total labor force) (modeled ilo estimate)",political stability and absence of violence/terrorism: estimate,"foreign direct investment, net inflows (% of gdp)","inflation, consumer prices (annual %)",access to electricity (% of population),mobile cellular subscriptions (per 100 people),population density (people per sq. km of land area),lending interest rate (%),"labor force participation rate, total (% of total population ages 15+) (modeled ilo estimate)",exports of goods and services (% of gdp),"government expenditure on education, total (% of gdp)","patent applications, residents","gni per capita, atlas method (current us$)",imports of goods and services (% of gdp),current health expenditure (% of gdp),renewable energy consumption (% of total final energy consumption),ratio of female to male labor force participation rate (%) (national estimate)
0,CA,92101,c:6669,San Diego,Bandsintown,1/1/2007,operating,4/1/2009,1/1/2010,2.2493,3.0027,4.6685,6.7041,3,375000,CA,1,0,0,0,0,music,0,0,0,0,0,0,0,0,0,1,c:6669,0,1,0,0,0,0,1.0000,0,acquired,/organization/bandsintown,http://www.bandsintown.com/home,Apps|Concerts|Ediscovery|Events|Facebook Appli...,375000,acquired,USA,CA,San Diego,San Diego,4.0,2007-01-01,2006-08-01,2010-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CA,95032,c:16283,Los Gatos,TriCipher,1/1/2000,operating,2/14/2005,12/28/2009,5.1260,9.9973,7.0055,7.0055,4,40100000,CA,1,0,0,0,0,enterprise,0,0,0,1,0,0,0,0,0,0,c:16283,1,0,0,1,1,1,4.7500,1,acquired,/organization/tricipher,http://www.tricipher.com,Enterprise Software,40100000,acquired,USA,CA,SF Bay Area,Los Gatos,4.0,2000-01-01,2005-02-14,2009-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CA,92121,c:65620,San Diego,Plixi,3/18/2009,operating,3/30/2010,3/30/2010,1.0329,1.0329,1.4575,2.2055,1,2600000,CA,1,0,0,0,0,web,0,1,0,0,0,0,0,0,0,0,c:65620,0,0,1,0,0,0,4.0000,1,acquired,/organization/plixi,http://plixi.com,Curated Web|Photography,2600000,acquired,USA,CA,San Diego,San Diego,1.0,2009-03-18,2010-03-30,2010-03-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CA,95014,c:42668,Cupertino,Solidcore Systems,1/1/2002,operating,2/17/2005,4/25/2007,3.1315,5.3151,6.0027,6.0027,3,40000000,CA,1,0,0,0,0,software,1,0,0,0,0,0,0,0,0,0,c:42668,0,0,0,1,1,1,3.3333,1,acquired,/organization/solidcore-systems,http://www.solidcore.com,Software,60950000,acquired,USA,CA,SF Bay Area,Cupertino,5.0,2002-01-01,2003-11-21,2008-08-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CA,94105,c:65806,San Francisco,Inhale Digital,8/1/2010,10/1/2012,8/1/2010,4/1/2012,0.0000,1.6685,0.0384,0.0384,2,1300000,CA,1,0,0,0,0,games_video,0,0,0,0,0,1,0,0,0,0,c:65806,1,1,0,0,0,0,1.0000,1,closed,/organization/inhale-digital,http://www.inhaledigital.com,Coupons|Facebook Applications|Flash Sales|Game...,1300000,closed,USA,CA,SF Bay Area,San Francisco,2.0,2010-08-01,2010-08-01,2012-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,CA,94107,c:21343,San Francisco,CoTweet,1/1/2009,operating,7/9/2009,7/9/2009,0.5178,0.5178,0.5808,4.5260,1,1100000,CA,1,0,0,0,0,advertising,0,0,0,0,1,0,0,0,0,0,c:21343,0,0,1,0,0,0,6.0000,1,acquired,/organization/cotweet,http://cotweet.com,Advertising|CRM|Twitter Applications,1100000,acquired,USA,CA,SF Bay Area,San Francisco,1.0,2009-01-01,2009-07-09,2009-07-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
924,MA,1803,c:41747,Burlington,Reef Point Systems,1/1/1998,6/25/2008,4/1/2005,3/23/2007,7.2521,9.2274,6.0027,6.0027,3,52000000,MA,0,0,1,0,0,security,0,0,0,0,0,0,0,0,0,1,c:41747,1,0,0,1,0,0,2.6667,1,closed,/organization/reef-point-systems,http://www.reefpoint.com,Security,52000000,closed,USA,MA,Boston,Burlington,3.0,1998-01-01,2005-04-01,2007-03-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
925,CA,94089,c:31549,Sunnyvale,Paracor Medical,1/1/1999,6/17/2012,6/29/2007,6/29/2007,8.4959,8.4959,9.0055,9.0055,1,44000000,CA,1,0,0,0,0,biotech,0,0,0,0,0,0,0,1,0,0,c:31549,0,0,0,0,0,1,8.0000,1,closed,/organization/paracor-medical,http://www.paracormedical.com,Health Care,44000000,closed,USA,CA,SF Bay Area,Sunnyvale,1.0,1999-01-01,2007-06-29,2007-06-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
926,CA,94404,c:33198,San Francisco,Causata,1/1/2009,operating,10/5/2009,11/1/2011,0.7589,2.8329,0.7589,3.8356,2,15500000,CA,1,0,0,0,0,software,1,0,0,0,0,0,0,0,0,0,c:33198,0,0,1,1,0,0,1.0000,1,acquired,/organization/causata,http://www.causata.com,Big Data|Predictive Analytics|Software,15500000,acquired,USA,CA,SF Bay Area,San Francisco,2.0,2009-01-01,2009-10-05,2011-11-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
927,CA,95054,c:26702,Santa Clara,Asempra Technologies,1/1/2003,operating,2/13/2006,2/13/2006,3.1205,3.1205,4.0027,4.0027,1,20000000,CA,1,0,0,0,0,security,0,0,0,0,0,0,0,0,0,1,c:26702,0,0,0,1,0,0,3.0000,1,acquired,/organization/asempra-technologies,NaN,Software,20000000,acquired,USA,CA,SF Bay Area,Santa Clara,1.0,2003-01-01,2006-02-13,2006-02-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
# Standardize column names in df_4 for consistency
df_4.columns = df_4.columns.str.lower()

# Merge df_4 with merged_df on the `company` column, adding relevant unicorn-related information
# Using a left join to keep all rows from merged_df
merged_df = pd.merge(merged_df, df_4[['company', 'valuation ($b)', 'date joined', 'industry']], 
                     how='left', left_on='name', right_on='company', suffixes=('', '_unicorn'))

# Drop the redundant 'company' column from df_4 after merging
merged_df = merged_df.drop(columns=['company'])

In [46]:
merged_df

,state_code_df1,zip_code,id,city_df1,name,founded_at_df1,closed_at,first_funding_at_df1,last_funding_at_df1,age_first_funding_year,age_last_funding_year,age_first_milestone_year,age_last_milestone_year,funding_rounds_df1,funding_total_usd_df1,state_code.1,is_ca,is_ny,is_ma,is_tx,is_otherstate,category_code,is_software,is_web,is_mobile,is_enterprise,is_advertising,is_gamesvideo,is_ecommerce,is_biotech,is_consulting,is_othercategory,object_id,has_vc,has_angel,has_rounda,has_roundb,has_roundc,has_roundd,avg_participants,is_top500,status_df1,permalink,homepage_url,category_list,funding_total_usd_df5,status_df5,country_code,state_code_df5,region,city_df5,funding_rounds_df5,founded_at_df5,first_funding_at_df5,last_funding_at_df5,year,country name,country code,"new business density (new registrations per 1,000 people ages 15-64)",research and development expenditure (% of gdp),market capitalization of listed domestic companies (% of gdp),individuals using the internet (% of population),"school enrollment, tertiary (% gross)","unemployment, total (% of total labor force) (modeled ilo estimate)",political stability and absence of violence/terrorism: estimate,"foreign direct investment, net inflows (% of gdp)","inflation, consumer prices (annual %)",access to electricity (% of population),mobile cellular subscriptions (per 100 people),population density (people per sq. km of land area),lending interest rate (%),"labor force participation rate, total (% of total population ages 15+) (modeled ilo estimate)",exports of goods and services (% of gdp),"government expenditure on education, total (% of gdp)","patent applications, residents","gni per capita, atlas method (current us$)",imports of goods and services (% of gdp),current health expenditure (% of gdp),renewable energy consumption (% of total final energy consumption),ratio of female to male labor force participation rate (%) (national estimate),valuation ($b),date joined,industry
0,CA,92101,c:6669,San Diego,Bandsintown,1/1/2007,operating,4/1/2009,1/1/2010,2.2493,3.0027,4.6685,6.7041,3,375000,CA,1,0,0,0,0,music,0,0,0,0,0,0,0,0,0,1,c:6669,0,1,0,0,0,0,1.0000,0,acquired,/organization/bandsintown,http://www.bandsintown.com/home,Apps|Concerts|Ediscovery|Events|Facebook Appli...,375000,acquired,USA,CA,San Diego,San Diego,4.0,2007-01-01,2006-08-01,2010-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CA,95032,c:16283,Los Gatos,TriCipher,1/1/2000,operating,2/14/2005,12/28/2009,5.1260,9.9973,7.0055,7.0055,4,40100000,CA,1,0,0,0,0,enterprise,0,0,0,1,0,0,0,0,0,0,c:16283,1,0,0,1,1,1,4.7500,1,acquired,/organization/tricipher,http://www.tricipher.com,Enterprise Software,40100000,acquired,USA,CA,SF Bay Area,Los Gatos,4.0,2000-01-01,2005-02-14,2009-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CA,92121,c:65620,San Diego,Plixi,3/18/2009,operating,3/30/2010,3/30/2010,1.0329,1.0329,1.4575,2.2055,1,2600000,CA,1,0,0,0,0,web,0,1,0,0,0,0,0,0,0,0,c:65620,0,0,1,0,0,0,4.0000,1,acquired,/organization/plixi,http://plixi.com,Curated Web|Photography,2600000,acquired,USA,CA,San Diego,San Diego,1.0,2009-03-18,2010-03-30,2010-03-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CA,95014,c:42668,Cupertino,Solidcore Systems,1/1/2002,operating,2/17/2005,4/25/2007,3.1315,5.3151,6.0027,6.0027,3,40000000,CA,1,0,0,0,0,software,1,0,0,0,0,0,0,0,0,0,c:42668,0,0,0,1,1,1,3.3333,1,acquired,/organization/solidcore-systems,http://www.solidcore.com,Software,60950000,acquired,USA,CA,SF Bay Area,Cupertino,5.0,2002-01-01,2003-11-21,2008-08-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CA,94105,c:65806,San Francisco,Inhale Digital,8/1/2010,10/1/2012,8/1/2010,4/1/2012,0.0000,1.6685,0.0384,0.0384,2,1300000,CA,1,0,0,0,0,games_video,0,0,0,0,0,1,0,0,0,0,c:65806,1,1,0,0,0,0,1.0000,1,closed,/organization/inhale-digital,http://www.inhaledigital.com,Coupons|Facebook Applications|Flash Sales|Game...,1300000,closed,USA,CA,SF Bay Area,San Francisco,2.0,2010-08-01,2010-08-01,2012-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,CA,94107,c:21343,San Francisco,CoTweet,1/1/2009,operating,7/9/2009,7/9/2009,0.5178,0.5178,0.5808,4.5260,1,1100000,CA,1,0,0,0,0,advertising,0,0,0,0,1,0,0,0,0,0,c:21343,0,0,1,0,0,0,6.0000,1,acquired,/organization/cotweet,http://cotweet.com,Advertising|CRM|Twitter Applications,1100000,acquired,USA,CA,SF Bay Area,San Francisco,1.0,2009-01-01,2009-07-09,2009-07-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
924,MA,1803,c:41747,Burlington,Reef Point Systems,1/1/1998,6/25/2008,4/1/2005,3/23/2007,7.2521,9.2274,6.0027,6.0027,3,52000000,MA,0,0,1,0,0,security,0,0,0,0,0,0,0,0,0,1,c:41747,1,0,0,1,0,0,2.6667,1,closed,/organization/reef-point-systems,http://www.reefpoint.com,Security,52000000,closed,USA,MA,Boston,Burlington,3.0,1998-01-01,2005-04-01,2007-03-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
925,CA,94089,c:31549,Sunnyvale,Paracor Medical,1/1/1999,6/17/2012,6/29/2007,6/29/2007,8.4959,8.4959,9.0055,9.0055,1,44000000,CA,1,0,0,0,0,biotech,0,0,0,0,0,0,0,1,0,0,c:31549,0,0,0,0,0,1,8.0000,1,closed,/organization/paracor-medical,http://www.paracormedical.com,Health Care,44000000,closed,USA,CA,SF Bay Area,Sunnyvale,1.0,1999-01-01,2007-06-29,2007-06-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
926,CA,94404,c:33198,San Francisco,Causata,1/1/2009,operating,10/5/2009,11/1/2011,0.7589,2.8329,0.7589,3.8356,2,15500000,CA,1,0,0,0,0,software,1,0,0,0,0,0,0,0,0,0,c:33198,0,0,1,1,0,0,1.0000,1,acquired,/organization/causata,http://www.causata.com,Big Data|Predictive Analytics|Software,15500000,acquired,USA,CA,SF Bay Area,San Francisco,2.0,2009-01-01,2009-10-05,2011-11-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
927,CA,95054,c:26702,Santa Clara,Asempra Technologies,1/1/2003,operating,2/13/2006,2/13/2006,3.1205,3.1205,4.0027,4.0027,1,20000000,CA,1,0,0,0,0,security,0,0,0,0,0,0,0,0,0,1,c:26702,0,0,0,1,0,0,3.0000,1,acquired,/organization/asempra-technologies,NaN,Software,20000000,acquired,USA,CA,SF Bay Area,Santa Clara,1.0,2003-01-01,2006-02-13,2006-02-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
# Fill missing values in unicorn-related columns to indicate non-unicorn status
merged_df['valuation ($b)'].fillna(0, inplace=True)
merged_df['date joined'].fillna("Not Available", inplace=True)
merged_df['industry'].fillna("Not Available", inplace=True)

# Impute missing values in economic indicators by country median or mean
economic_columns = [
    'new business density (new registrations per 1,000 people ages 15-64)',
    'research and development expenditure (% of gdp)',
    'market capitalization of listed domestic companies (% of gdp)',
    'individuals using the internet (% of population)',
    'school enrollment, tertiary (% gross)',
    'unemployment, total (% of total labor force) (modeled ilo estimate)',
    'political stability and absence of violence/terrorism: estimate',
    'foreign direct investment, net inflows (% of gdp)',
    'inflation, consumer prices (annual %)',
    'access to electricity (% of population)',
    'mobile cellular subscriptions (per 100 people)',
    'population density (people per sq. km of land area)'
]

for col in economic_columns:
    merged_df[col] = merged_df.groupby('country code')[col].transform(lambda x: x.fillna(x.median()))

# Drop columns with high missing values if not critical to the model
merged_df.dropna(axis=1, thresh=int(0.5 * len(merged_df)), inplace=True)  # drops columns with more than 50% missing values

/var/folders/1p/3nvyb0qn4zbfkzm72nmsffqh0000gn/T/ipykernel_13055/3402536980.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['valuation ($b)'].fillna(0, inplace=True)
/var/folders/1p/3nvyb0qn4zbfkzm72nmsffqh0000gn/T/ipykernel_13055/3402536980.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  merged_df['valuation ($b)'].fillna(0, inplace=True)
/var/folders/1p/3nvyb0qn4zbfkzm72nmsffqh0000gn/T/ipykernel_13055/3402536980.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['date joined'].fillna("Not Available", inplace=True)
/var/folders/1p/3nvyb0qn4zbfkzm72nmsffqh0000gn/T/ipykernel_13055/3402536980.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['industry'].fillna("Not Available", inplace=True)

In [48]:
merged_df

,state_code_df1,zip_code,id,city_df1,name,founded_at_df1,closed_at,first_funding_at_df1,last_funding_at_df1,age_first_funding_year,age_last_funding_year,age_first_milestone_year,age_last_milestone_year,funding_rounds_df1,funding_total_usd_df1,state_code.1,is_ca,is_ny,is_ma,is_tx,is_otherstate,category_code,is_software,is_web,is_mobile,is_enterprise,is_advertising,is_gamesvideo,is_ecommerce,is_biotech,is_consulting,is_othercategory,object_id,has_vc,has_angel,has_rounda,has_roundb,has_roundc,has_roundd,avg_participants,is_top500,status_df1,permalink,homepage_url,category_list,funding_total_usd_df5,status_df5,country_code,state_code_df5,region,city_df5,funding_rounds_df5,founded_at_df5,first_funding_at_df5,last_funding_at_df5,valuation ($b),date joined,industry
0,CA,92101,c:6669,San Diego,Bandsintown,1/1/2007,operating,4/1/2009,1/1/2010,2.2493,3.0027,4.6685,6.7041,3,375000,CA,1,0,0,0,0,music,0,0,0,0,0,0,0,0,0,1,c:6669,0,1,0,0,0,0,1.0000,0,acquired,/organization/bandsintown,http://www.bandsintown.com/home,Apps|Concerts|Ediscovery|Events|Facebook Appli...,375000,acquired,USA,CA,San Diego,San Diego,4.0,2007-01-01,2006-08-01,2010-01-01,0,Not Available,Not Available
1,CA,95032,c:16283,Los Gatos,TriCipher,1/1/2000,operating,2/14/2005,12/28/2009,5.1260,9.9973,7.0055,7.0055,4,40100000,CA,1,0,0,0,0,enterprise,0,0,0,1,0,0,0,0,0,0,c:16283,1,0,0,1,1,1,4.7500,1,acquired,/organization/tricipher,http://www.tricipher.com,Enterprise Software,40100000,acquired,USA,CA,SF Bay Area,Los Gatos,4.0,2000-01-01,2005-02-14,2009-12-28,0,Not Available,Not Available
2,CA,92121,c:65620,San Diego,Plixi,3/18/2009,operating,3/30/2010,3/30/2010,1.0329,1.0329,1.4575,2.2055,1,2600000,CA,1,0,0,0,0,web,0,1,0,0,0,0,0,0,0,0,c:65620,0,0,1,0,0,0,4.0000,1,acquired,/organization/plixi,http://plixi.com,Curated Web|Photography,2600000,acquired,USA,CA,San Diego,San Diego,1.0,2009-03-18,2010-03-30,2010-03-30,0,Not Available,Not Available
3,CA,95014,c:42668,Cupertino,Solidcore Systems,1/1/2002,operating,2/17/2005,4/25/2007,3.1315,5.3151,6.0027,6.0027,3,40000000,CA,1,0,0,0,0,software,1,0,0,0,0,0,0,0,0,0,c:42668,0,0,0,1,1,1,3.3333,1,acquired,/organization/solidcore-systems,http://www.solidcore.com,Software,60950000,acquired,USA,CA,SF Bay Area,Cupertino,5.0,2002-01-01,2003-11-21,2008-08-08,0,Not Available,Not Available
4,CA,94105,c:65806,San Francisco,Inhale Digital,8/1/2010,10/1/2012,8/1/2010,4/1/2012,0.0000,1.6685,0.0384,0.0384,2,1300000,CA,1,0,0,0,0,games_video,0,0,0,0,0,1,0,0,0,0,c:65806,1,1,0,0,0,0,1.0000,1,closed,/organization/inhale-digital,http://www.inhaledigital.com,Coupons|Facebook Applications|Flash Sales|Game...,1300000,closed,USA,CA,SF Bay Area,San Francisco,2.0,2010-08-01,2010-08-01,2012-04-01,0,Not Available,Not Available
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,CA,94107,c:21343,San Francisco,CoTweet,1/1/2009,operating,7/9/2009,7/9/2009,0.5178,0.5178,0.5808,4.5260,1,1100000,CA,1,0,0,0,0,advertising,0,0,0,0,1,0,0,0,0,0,c:21343,0,0,1,0,0,0,6.0000,1,acquired,/organization/cotweet,http://cotweet.com,Advertising|CRM|Twitter Applications,1100000,acquired,USA,CA,SF Bay Area,San Francisco,1.0,2009-01-01,2009-07-09,2009-07-09,0,Not Available,Not Available
924,MA,1803,c:41747,Burlington,Reef Point Systems,1/1/1998,6/25/2008,4/1/2005,3/23/2007,7.2521,9.2274,6.0027,6.0027,3,52000000,MA,0,0,1,0,0,security,0,0,0,0,0,0,0,0,0,1,c:41747,1,0,0,1,0,0,2.6667,1,closed,/organization/reef-point-systems,http://www.reefpoint.com,Security,52000000,closed,USA,MA,Boston,Burlington,3.0,1998-01-01,2005-04-01,2007-03-23,0,Not Available,Not Available
925,CA,94089,c:31549,Sunnyvale,Paracor Medical,1/1/1999,6/17/2012,6/29/2007,6/29/2007,8.4959,8.4959,9.0055,9.0055,1,44000000,CA,1,0,0,0,0,biotech,0,0,0,0,0,0,0,1,0,0,c:31549,0,0,0,0,0,1,8.0000,1,closed,/organization/paracor-medical,http://www.paracormedical.com,Health Care,44000000,closed,USA,CA,SF Bay Area,Sunnyvale,1.0,1999-01-01,2007-06-29,2007-06-29,0,Not Available,Not Available
926,CA,94404,c:33198,San Francisco,Causata,1/1/2009,operating,10/5/2009,11/1/2011,0.7589,2.8329,0.7589,3.8356,2,15500000,CA,1,0,0,0,0,software,1,0,0,0,0,0,0,0,0,0,c:33198,0,0,1,1,0,0,1.0000,1,acquired,/organization/causata,http://www.causata.com,Big Data|Predictive Analytics|Software,15500000,acquired,USA,CA,SF Bay Area,San Francisco,2.0,2009-01-01,2009-10-05,2011-11-01,0,Not Available,Not Available
927,CA,95054,c:26702,Santa Clara,Asempra Technologies,1/1/2003,operating,2/13/2006,2/13/2006,3.1205,3.1205,4.0027,4.0027,1,20000000,CA,1,0,0,0,0,security,0,0,0,0,0,0,0,0,0,1,c:26702,0,0,0,1,0,0,3.0000,1,acquired,/organization/asempra-technologies,NaN,Software,20000000,acquired,USA,CA,SF Bay Area,Santa Clara,1.0,2003-01-01,2006-02-13,2006-02-13,0,Not Available,Not Available

In [49]:
# Set Pandas options to display all columns
pd.set_option('display.max_columns', None)

# Display the DataFrame
merged_df.head()

,state_code_df1,zip_code,id,city_df1,name,founded_at_df1,closed_at,first_funding_at_df1,last_funding_at_df1,age_first_funding_year,age_last_funding_year,age_first_milestone_year,age_last_milestone_year,funding_rounds_df1,funding_total_usd_df1,state_code.1,is_ca,is_ny,is_ma,is_tx,is_otherstate,category_code,is_software,is_web,is_mobile,is_enterprise,is_advertising,is_gamesvideo,is_ecommerce,is_biotech,is_consulting,is_othercategory,object_id,has_vc,has_angel,has_rounda,has_roundb,has_roundc,has_roundd,avg_participants,is_top500,status_df1,permalink,homepage_url,category_list,funding_total_usd_df5,status_df5,country_code,state_code_df5,region,city_df5,funding_rounds_df5,founded_at_df5,first_funding_at_df5,last_funding_at_df5,valuation ($b),date joined,industry
0,CA,92101,c:6669,San Diego,Bandsintown,1/1/2007,operating,4/1/2009,1/1/2010,2.2493,3.0027,4.6685,6.7041,3,375000,CA,1,0,0,0,0,music,0,0,0,0,0,0,0,0,0,1,c:6669,0,1,0,0,0,0,1.0000,0,acquired,/organization/bandsintown,http://www.bandsintown.com/home,Apps|Concerts|Ediscovery|Events|Facebook Appli...,375000,acquired,USA,CA,San Diego,San Diego,4.0,2007-01-01,2006-08-01,2010-01-01,0,Not Available,Not Available
1,CA,95032,c:16283,Los Gatos,TriCipher,1/1/2000,operating,2/14/2005,12/28/2009,5.1260,9.9973,7.0055,7.0055,4,40100000,CA,1,0,0,0,0,enterprise,0,0,0,1,0,0,0,0,0,0,c:16283,1,0,0,1,1,1,4.7500,1,acquired,/organization/tricipher,http://www.tricipher.com,Enterprise Software,40100000,acquired,USA,CA,SF Bay Area,Los Gatos,4.0,2000-01-01,2005-02-14,2009-12-28,0,Not Available,Not Available
2,CA,92121,c:65620,San Diego,Plixi,3/18/2009,operating,3/30/2010,3/30/2010,1.0329,1.0329,1.4575,2.2055,1,2600000,CA,1,0,0,0,0,web,0,1,0,0,0,0,0,0,0,0,c:65620,0,0,1,0,0,0,4.0000,1,acquired,/organization/plixi,http://plixi.com,Curated Web|Photography,2600000,acquired,USA,CA,San Diego,San Diego,1.0,2009-03-18,2010-03-30,2010-03-30,0,Not Available,Not Available
3,CA,95014,c:42668,Cupertino,Solidcore Systems,1/1/2002,operating,2/17/2005,4/25/2007,3.1315,5.3151,6.0027,6.0027,3,40000000,CA,1,0,0,0,0,software,1,0,0,0,0,0,0,0,0,0,c:42668,0,0,0,1,1,1,3.3333,1,acquired,/organization/solidcore-systems,http://www.solidcore.com,Software,60950000,acquired,USA,CA,SF Bay Area,Cupertino,5.0,2002-01-01,2003-11-21,2008-08-08,0,Not Available,Not Available
4,CA,94105,c:65806,San Francisco,Inhale Digital,8/1/2010,10/1/2012,8/1/2010,4/1/2012,0.0000,1.6685,0.0384,0.0384,2,1300000,CA,1,0,0,0,0,games_video,0,0,0,0,0,1,0,0,0,0,c:65806,1,1,0,0,0,0,1.0000,1,closed,/organization/inhale-digital,http://www.inhaledigital.com,Coupons|Facebook Applications|Flash Sales|Game...,1300000,closed,USA,CA,SF Bay Area,San Francisco,2.0,2010-08-01,2010-08-01,2012-04-01,0,Not Available,Not Available

Columns in dataset:
1.	Location and Company Identifiers: state_code_df1, zip_code, id, city_df1, name
2.	Funding and Milestone Information: founded_at_df1, closed_at, first_funding_at_df1, last_funding_at_df1, funding_rounds_df1, funding_total_usd_df1
3.	Category and Industry Flags: Columns such as category_code, is_software, is_web, is_mobile
4.	Investor and Round Information: has_vc, has_angel, has_rounda, has_roundb, etc.
5.	Unicorn Data: valuation ($b), date joined, industry
6.	Economic Indicators: Various columns from df_3, including new business density, political stability, etc.

In [50]:
# List all column names to verify exact names
print(merged_df.columns.tolist())

['state_code_df1', 'zip_code', 'id', 'city_df1', 'name', 'founded_at_df1', 'closed_at', 'first_funding_at_df1', 'last_funding_at_df1', 'age_first_funding_year', 'age_last_funding_year', 'age_first_milestone_year', 'age_last_milestone_year', 'funding_rounds_df1', 'funding_total_usd_df1', 'state_code.1', 'is_ca', 'is_ny', 'is_ma', 'is_tx', 'is_otherstate', 'category_code', 'is_software', 'is_web', 'is_mobile', 'is_enterprise', 'is_advertising', 'is_gamesvideo', 'is_ecommerce', 'is_biotech', 'is_consulting', 'is_othercategory', 'object_id', 'has_vc', 'has_angel', 'has_rounda', 'has_roundb', 'has_roundc', 'has_roundd', 'avg_participants', 'is_top500', 'status_df1', 'permalink', 'homepage_url', 'category_list', 'funding_total_usd_df5', 'status_df5', 'country_code', 'state_code_df5', 'region', 'city_df5', 'funding_rounds_df5', 'founded_at_df5', 'first_funding_at_df5', 'last_funding_at_df5', 'valuation ($b)', 'date joined', 'industry']

In [51]:
columns_to_keep = [
    'name', 'city_df1', 'state_code_df1', 'country_code',
    'founded_at_df1', 'first_funding_at_df1', 'last_funding_at_df1',
    'age_first_funding_year', 'age_last_funding_year', 'funding_rounds_df1', 'funding_total_usd_df1',
    'has_vc', 'has_angel', 'has_rounda', 'has_roundb', 'has_roundc', 'has_roundd',
    'category_code', 'is_software', 'is_web', 'is_mobile', 'is_enterprise', 'is_advertising',
    'is_gamesvideo', 'is_ecommerce', 'is_biotech', 'is_consulting', 'is_othercategory',
    'valuation ($b)', 'industry', 'status_df1'
]

In [52]:
# Select only the relevant columns for the final dataset
final_df = merged_df[columns_to_keep]

# Display the final dataframe
final_df

,name,city_df1,state_code_df1,country_code,founded_at_df1,first_funding_at_df1,last_funding_at_df1,age_first_funding_year,age_last_funding_year,funding_rounds_df1,funding_total_usd_df1,has_vc,has_angel,has_rounda,has_roundb,has_roundc,has_roundd,category_code,is_software,is_web,is_mobile,is_enterprise,is_advertising,is_gamesvideo,is_ecommerce,is_biotech,is_consulting,is_othercategory,valuation ($b),industry,status_df1
0,Bandsintown,San Diego,CA,USA,1/1/2007,4/1/2009,1/1/2010,2.2493,3.0027,3,375000,0,1,0,0,0,0,music,0,0,0,0,0,0,0,0,0,1,0,Not Available,acquired
1,TriCipher,Los Gatos,CA,USA,1/1/2000,2/14/2005,12/28/2009,5.1260,9.9973,4,40100000,1,0,0,1,1,1,enterprise,0,0,0,1,0,0,0,0,0,0,0,Not Available,acquired
2,Plixi,San Diego,CA,USA,3/18/2009,3/30/2010,3/30/2010,1.0329,1.0329,1,2600000,0,0,1,0,0,0,web,0,1,0,0,0,0,0,0,0,0,0,Not Available,acquired
3,Solidcore Systems,Cupertino,CA,USA,1/1/2002,2/17/2005,4/25/2007,3.1315,5.3151,3,40000000,0,0,0,1,1,1,software,1,0,0,0,0,0,0,0,0,0,0,Not Available,acquired
4,Inhale Digital,San Francisco,CA,USA,8/1/2010,8/1/2010,4/1/2012,0.0000,1.6685,2,1300000,1,1,0,0,0,0,games_video,0,0,0,0,0,1,0,0,0,0,0,Not Available,closed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,CoTweet,San Francisco,CA,USA,1/1/2009,7/9/2009,7/9/2009,0.5178,0.5178,1,1100000,0,0,1,0,0,0,advertising,0,0,0,0,1,0,0,0,0,0,0,Not Available,acquired
924,Reef Point Systems,Burlington,MA,USA,1/1/1998,4/1/2005,3/23/2007,7.2521,9.2274,3,52000000,1,0,0,1,0,0,security,0,0,0,0,0,0,0,0,0,1,0,Not Available,closed
925,Paracor Medical,Sunnyvale,CA,USA,1/1/1999,6/29/2007,6/29/2007,8.4959,8.4959,1,44000000,0,0,0,0,0,1,biotech,0,0,0,0,0,0,0,1,0,0,0,Not Available,closed
926,Causata,San Francisco,CA,USA,1/1/2009,10/5/2009,11/1/2011,0.7589,2.8329,2,15500000,0,0,1,1,0,0,software,1,0,0,0,0,0,0,0,0,0,0,Not Available,acquired
927,Asempra Technologies,Santa Clara,CA,USA,1/1/2003,2/13/2006,2/13/2006,3.1205,3.1205,1,20000000,0,0,0,1,0,0,security,0,0,0,0,0,0,0,0,0,1,0,Not Available,acquired

In [53]:
from sklearn.preprocessing import LabelEncoder

# Encode target variable 'status_df1'
label_encoder = LabelEncoder()
final_df['status_encoded'] = label_encoder.fit_transform(final_df['status_df1'])

# Encode other categorical features
final_df['category_code_encoded'] = label_encoder.fit_transform(final_df['category_code'].fillna('Unknown'))
final_df['industry_encoded'] = label_encoder.fit_transform(final_df['industry'].fillna('Unknown'))

# Drop original categorical columns
final_df = final_df.drop(columns=['status_df1', 'category_code', 'industry'])

# Display the first few rows to check encodings
print(final_df[['status_encoded', 'category_code_encoded', 'industry_encoded']].head())

   status_encoded  category_code_encoded  industry_encoded
0               0                     19                 0
1               0                      8                 0
2               0                     34                 0
3               0                     30                 0
4               1                     11                 0

/var/folders/1p/3nvyb0qn4zbfkzm72nmsffqh0000gn/T/ipykernel_13055/2772661785.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['status_encoded'] = label_encoder.fit_transform(final_df['status_df1'])
/var/folders/1p/3nvyb0qn4zbfkzm72nmsffqh0000gn/T/ipykernel_13055/2772661785.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['category_code_encoded'] = label_encoder.fit_transform(final_df['category_code'].fillna('Unknown'))
/var/folders/1p/3nvyb0qn4zbfkzm72nmsffqh0000gn/T/ipykernel_13055/2772661785.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['industry_encoded'] = label_encoder.fit_transform(final_df['industry'].fillna('Unknown'))

In [54]:
# Check for missing values in each column
missing_values = final_df.isnull().sum()
print(missing_values[missing_values > 0])

country_code    29
dtype: int64

In [55]:
# Define a dictionary mapping state codes to country codes for common states
state_to_country = {
    'CA': 'USA',
    'NY': 'USA',
    'TX': 'USA',
    'MA': 'USA',
    'ON': 'CAN',  
}

# Apply this mapping to fill missing country codes where possible
final_df['country_code'] = final_df.apply(
    lambda row: state_to_country.get(row['state_code_df1'], row['country_code']),
    axis=1
)

# Check if there are any remaining missing values
print(final_df['country_code'].isnull().sum())

4

In [56]:
# Drop rows where 'country_code' is still missing
final_df = final_df.dropna(subset=['country_code'])

# Confirm no missing values remain in 'country_code'
print(final_df['country_code'].isnull().sum())

0

In [58]:
# Display the column names in final_df
print(final_df.columns)

Index(['name', 'city_df1', 'state_code_df1', 'country_code', 'founded_at_df1',
       'first_funding_at_df1', 'last_funding_at_df1', 'age_first_funding_year',
       'age_last_funding_year', 'funding_rounds_df1', 'funding_total_usd_df1',
       'has_vc', 'has_angel', 'has_rounda', 'has_roundb', 'has_roundc',
       'has_roundd', 'is_software', 'is_web', 'is_mobile', 'is_enterprise',
       'is_advertising', 'is_gamesvideo', 'is_ecommerce', 'is_biotech',
       'is_consulting', 'is_othercategory', 'valuation ($b)', 'status_encoded',
       'category_code_encoded', 'industry_encoded'],
      dtype='object')

In [59]:
# Drop redundant unencoded columns
final_df.drop(columns=['status_df1', 'category_code', 'industry'], errors='ignore', inplace=True)

# Proceed to check the final structure and ensure all data is numeric
print(final_df.head())
print(final_df.info())  # Confirm all columns are now numeric or in a usable form

                name       city_df1 state_code_df1 country_code  \
0        Bandsintown      San Diego             CA          USA
1          TriCipher      Los Gatos             CA          USA
2              Plixi      San Diego             CA          USA
3  Solidcore Systems      Cupertino             CA          USA
4     Inhale Digital  San Francisco             CA          USA

  founded_at_df1 first_funding_at_df1 last_funding_at_df1  \
0       1/1/2007             4/1/2009            1/1/2010
1       1/1/2000            2/14/2005          12/28/2009
2      3/18/2009            3/30/2010           3/30/2010
3       1/1/2002            2/17/2005           4/25/2007
4       8/1/2010             8/1/2010            4/1/2012

   age_first_funding_year  age_last_funding_year  funding_rounds_df1  \
0                  2.2493                 3.0027                   3
1                  5.1260                 9.9973                   4
2                  1.0329                 1.0329                   1
3                  3.1315                 5.3151                   3
4                  0.0000                 1.6685                   2

   funding_total_usd_df1  has_vc  has_angel  has_rounda  has_roundb  \
0                 375000       0          1           0           0
1               40100000       1          0           0           1
2                2600000       0          0           1           0
3               40000000       0          0           0           1
4                1300000       1          1           0           0

   has_roundc  has_roundd  is_software  is_web  is_mobile  is_enterprise  \
0           0           0            0       0          0              0
1           1           1            0       0          0              1
2           0           0            0       1          0              0
3           1           1            1       0          0              0
4           0           0            0       0          0              0

   is_advertising  is_gamesvideo  is_ecommerce  is_biotech  is_consulting  \
0               0              0             0           0              0
1               0              0             0           0              0
2               0              0             0           0              0
3               0              0             0           0              0
4               0              1             0           0              0

   is_othercategory  valuation ($b)  status_encoded  category_code_encoded  \
0                 1               0               0                     19
1                 0               0               0                      8
2                 0               0               0                     34
3                 0               0               0                     30
4                 0               0               1                     11

   industry_encoded
0                 0
1                 0
2                 0
3                 0
4                 0
<class 'pandas.core.frame.DataFrame'>
Index: 924 entries, 0 to 927
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   name                    924 non-null    object
 1   city_df1                924 non-null    object
 2   state_code_df1          924 non-null    object
 3   country_code            924 non-null    object
 4   founded_at_df1          924 non-null    object
 5   first_funding_at_df1    924 non-null    object
 6   last_funding_at_df1     924 non-null    object
 7   age_first_funding_year  924 non-null    float64
 8   age_last_funding_year   924 non-null    float64
 9   funding_rounds_df1      924 non-null    int64
 10  funding_total_usd_df1   924 non-null    int64
 11  has_vc                  924 non-null    int64
 12  has_angel               924 non-null    int64
 13  has_rounda              924 non-null    int64
 14  has_roundb              924 non-null    int64
 15  has_roundc              924 non-null    int64
 16  has_roundd              924 non-null    int64
 17  is_software             924 non-null    int64
 18  is_web                  924 non-null    int64
 19  is_mobile               924 non-null    int64
 20  is_enterprise           924 non-null    int64
 21  is_advertising          924 non-null    int64
 22  is_gamesvideo           924 non-null    int64
 23  is_ecommerce            924 non-null    int64
 24  is_biotech              924 non-null    int64
 25  is_consulting           924 non-null    int64
 26  is_othercategory        924 non-null    int64
 27  valuation ($b)          924 non-null    int64
 28  status_encoded          924 non-null    int64
 29  category_code_encoded   924 non-null    int64
 30  industry_encoded        924 non-null    int64
dtypes: float64(2), int64(22), object(7)
memory usage: 231.0+ KB
None

In [60]:
# Convert date columns to datetime format
final_df['founded_at_df1'] = pd.to_datetime(final_df['founded_at_df1'], errors='coerce')
final_df['first_funding_at_df1'] = pd.to_datetime(final_df['first_funding_at_df1'], errors='coerce')
final_df['last_funding_at_df1'] = pd.to_datetime(final_df['last_funding_at_df1'], errors='coerce')

# Create a new column for the company's age at first funding
final_df['age_at_first_funding'] = (final_df['first_funding_at_df1'] - final_df['founded_at_df1']).dt.days / 365

# Drop the original date columns now that we’ve extracted relevant information
final_df.drop(columns=['founded_at_df1', 'first_funding_at_df1', 'last_funding_at_df1'], inplace=True)

# Verify changes
print(final_df.head())
print(final_df.info())

                name       city_df1 state_code_df1 country_code  \
0        Bandsintown      San Diego             CA          USA
1          TriCipher      Los Gatos             CA          USA
2              Plixi      San Diego             CA          USA
3  Solidcore Systems      Cupertino             CA          USA
4     Inhale Digital  San Francisco             CA          USA

   age_first_funding_year  age_last_funding_year  funding_rounds_df1  \
0                  2.2493                 3.0027                   3
1                  5.1260                 9.9973                   4
2                  1.0329                 1.0329                   1
3                  3.1315                 5.3151                   3
4                  0.0000                 1.6685                   2

   funding_total_usd_df1  has_vc  has_angel  has_rounda  has_roundb  \
0                 375000       0          1           0           0
1               40100000       1          0           0           1
2                2600000       0          0           1           0
3               40000000       0          0           0           1
4                1300000       1          1           0           0

   has_roundc  has_roundd  is_software  is_web  is_mobile  is_enterprise  \
0           0           0            0       0          0              0
1           1           1            0       0          0              1
2           0           0            0       1          0              0
3           1           1            1       0          0              0
4           0           0            0       0          0              0

   is_advertising  is_gamesvideo  is_ecommerce  is_biotech  is_consulting  \
0               0              0             0           0              0
1               0              0             0           0              0
2               0              0             0           0              0
3               0              0             0           0              0
4               0              1             0           0              0

   is_othercategory  valuation ($b)  status_encoded  category_code_encoded  \
0                 1               0               0                     19
1                 0               0               0                      8
2                 0               0               0                     34
3                 0               0               0                     30
4                 0               0               1                     11

   industry_encoded  age_at_first_funding
0                 0              2.249315
1                 0              5.126027
2                 0              1.032877
3                 0              3.131507
4                 0              0.000000
<class 'pandas.core.frame.DataFrame'>
Index: 924 entries, 0 to 927
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   name                    924 non-null    object
 1   city_df1                924 non-null    object
 2   state_code_df1          924 non-null    object
 3   country_code            924 non-null    object
 4   age_first_funding_year  924 non-null    float64
 5   age_last_funding_year   924 non-null    float64
 6   funding_rounds_df1      924 non-null    int64
 7   funding_total_usd_df1   924 non-null    int64
 8   has_vc                  924 non-null    int64
 9   has_angel               924 non-null    int64
 10  has_rounda              924 non-null    int64
 11  has_roundb              924 non-null    int64
 12  has_roundc              924 non-null    int64
 13  has_roundd              924 non-null    int64
 14  is_software             924 non-null    int64
 15  is_web                  924 non-null    int64
 16  is_mobile               924 non-null    int64
 17  is_enterprise           924 non-null    int64
 18  is_advertising          924 non-null    int64
 19  is_gamesvideo           924 non-null    int64
 20  is_ecommerce            924 non-null    int64
 21  is_biotech              924 non-null    int64
 22  is_consulting           924 non-null    int64
 23  is_othercategory        924 non-null    int64
 24  valuation ($b)          924 non-null    int64
 25  status_encoded          924 non-null    int64
 26  category_code_encoded   924 non-null    int64
 27  industry_encoded        924 non-null    int64
 28  age_at_first_funding    924 non-null    float64
dtypes: float64(3), int64(22), object(4)
memory usage: 216.6+ KB
None

In [61]:
# Drop non-essential columns if they are irrelevant to the model
final_df.drop(columns=['name', 'city_df1'], inplace=True)

# One-hot encode `state_code_df1` and `country_code`
final_df = pd.get_dummies(final_df, columns=['state_code_df1', 'country_code'], drop_first=True)

# Verify the final structure
print(final_df.head())
print(final_df.info())

   age_first_funding_year  age_last_funding_year  funding_rounds_df1  \
0                  2.2493                 3.0027                   3
1                  5.1260                 9.9973                   4
2                  1.0329                 1.0329                   1
3                  3.1315                 5.3151                   3
4                  0.0000                 1.6685                   2

   funding_total_usd_df1  has_vc  has_angel  has_rounda  has_roundb  \
0                 375000       0          1           0           0
1               40100000       1          0           0           1
2                2600000       0          0           1           0
3               40000000       0          0           0           1
4                1300000       1          1           0           0

   has_roundc  has_roundd  is_software  is_web  is_mobile  is_enterprise  \
0           0           0            0       0          0              0
1           1           1            0       0          0              1
2           0           0            0       1          0              0
3           1           1            1       0          0              0
4           0           0            0       0          0              0

   is_advertising  is_gamesvideo  is_ecommerce  is_biotech  is_consulting  \
0               0              0             0           0              0
1               0              0             0           0              0
2               0              0             0           0              0
3               0              0             0           0              0
4               0              1             0           0              0

   is_othercategory  valuation ($b)  status_encoded  category_code_encoded  \
0                 1               0               0                     19
1                 0               0               0                      8
2                 0               0               0                     34
3                 0               0               0                     30
4                 0               0               1                     11

   industry_encoded  age_at_first_funding  state_code_df1_AZ  \
0                 0              2.249315              False
1                 0              5.126027              False
2                 0              1.032877              False
3                 0              3.131507              False
4                 0              0.000000              False

   state_code_df1_CA  state_code_df1_CO  state_code_df1_CT  state_code_df1_DC  \
0               True              False              False              False
1               True              False              False              False
2               True              False              False              False
3               True              False              False              False
4               True              False              False              False

   state_code_df1_FL  state_code_df1_GA  state_code_df1_ID  state_code_df1_IL  \
0              False              False              False              False
1              False              False              False              False
2              False              False              False              False
3              False              False              False              False
4              False              False              False              False

   state_code_df1_IN  state_code_df1_KY  state_code_df1_MA  state_code_df1_MD  \
0              False              False              False              False
1              False              False              False              False
2              False              False              False              False
3              False              False              False              False
4              False              False              False              False

   state_code_df1_ME  state_code_df1_MI  state_code_df1_MN  state_code_df1_MO  \
0              False              False              False              False
1              False              False              False              False
2              False              False              False              False
3              False              False              False              False
4              False              False              False              False

   state_code_df1_NC  state_code_df1_NH  state_code_df1_NJ  state_code_df1_NM  \
0              False              False              False              False
1              False              False              False              False
2              False              False              False              False
3              False              False              False              False
4              False              False              False              False

   state_code_df1_NV  state_code_df1_NY  state_code_df1_OH  state_code_df1_OR  \
0              False              False              False              False
1              False              False              False              False
2              False              False              False              False
3              False              False              False              False
4              False              False              False              False

   state_code_df1_PA  state_code_df1_RI  state_code_df1_TN  state_code_df1_TX  \
0              False              False              False              False
1              False              False              False              False
2              False              False              False              False
3              False              False              False              False
4              False              False              False              False

   state_code_df1_UT  state_code_df1_VA  state_code_df1_WA  state_code_df1_WI  \
0              False              False              False              False
1              False              False              False              False
2              False              False              False              False
3              False              False              False              False
4              False              False              False              False

   state_code_df1_WV
0              False
1              False
2              False
3              False
4              False
<class 'pandas.core.frame.DataFrame'>
Index: 924 entries, 0 to 927
Data columns (total 59 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   age_first_funding_year  924 non-null    float64
 1   age_last_funding_year   924 non-null    float64
 2   funding_rounds_df1      924 non-null    int64
 3   funding_total_usd_df1   924 non-null    int64
 4   has_vc                  924 non-null    int64
 5   has_angel               924 non-null    int64
 6   has_rounda              924 non-null    int64
 7   has_roundb              924 non-null    int64
 8   has_roundc              924 non-null    int64
 9   has_roundd              924 non-null    int64
 10  is_software             924 non-null    int64
 11  is_web                  924 non-null    int64
 12  is_mobile               924 non-null    int64
 13  is_enterprise           924 non-null    int64
 14  is_advertising          924 non-null    int64
 15  is_gamesvideo           924 non-null    int64
 16  is_ecommerce            924 non-null    int64
 17  is_biotech              924 non-null    int64
 18  is_consulting           924 non-null    int64
 19  is_othercategory        924 non-null    int64
 20  valuation ($b)          924 non-null    int64
 21  status_encoded          924 non-null    int64
 22  category_code_encoded   924 non-null    int64
 23  industry_encoded        924 non-null    int64
 24  age_at_first_funding    924 non-null    float64
 25  state_code_df1_AZ       924 non-null    bool
 26  state_code_df1_CA       924 non-null    bool
 27  state_code_df1_CO       924 non-null    bool
 28  state_code_df1_CT       924 non-null    bool
 29  state_code_df1_DC       924 non-null    bool
 30  state_code_df1_FL       924 non-null    bool
 31  state_code_df1_GA       924 non-null    bool
 32  state_code_df1_ID       924 non-null    bool
 33  state_code_df1_IL       924 non-null    bool
 34  state_code_df1_IN       924 non-null    bool
 35  state_code_df1_KY       924 non-null    bool
 36  state_code_df1_MA       924 non-null    bool
 37  state_code_df1_MD       924 non-null    bool
 38  state_code_df1_ME       924 non-null    bool
 39  state_code_df1_MI       924 non-null    bool
 40  state_code_df1_MN       924 non-null    bool
 41  state_code_df1_MO       924 non-null    bool
 42  state_code_df1_NC       924 non-null    bool
 43  state_code_df1_NH       924 non-null    bool
 44  state_code_df1_NJ       924 non-null    bool
 45  state_code_df1_NM       924 non-null    bool
 46  state_code_df1_NV       924 non-null    bool
 47  state_code_df1_NY       924 non-null    bool
 48  state_code_df1_OH       924 non-null    bool
 49  state_code_df1_OR       924 non-null    bool
 50  state_code_df1_PA       924 non-null    bool
 51  state_code_df1_RI       924 non-null    bool
 52  state_code_df1_TN       924 non-null    bool
 53  state_code_df1_TX       924 non-null    bool
 54  state_code_df1_UT       924 non-null    bool
 55  state_code_df1_VA       924 non-null    bool
 56  state_code_df1_WA       924 non-null    bool
 57  state_code_df1_WI       924 non-null    bool
 58  state_code_df1_WV       924 non-null    bool
dtypes: bool(34), float64(3), int64(22)
memory usage: 218.4 KB
None

In [62]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = StandardScaler()

# Selecting numerical columns for scaling (exclude target and any already encoded columns if needed)
numerical_features = [
    'age_first_funding_year', 'age_last_funding_year', 'funding_rounds_df1', 
    'funding_total_usd_df1', 'valuation ($b)'
]

# Fit and transform the scaler
final_df[numerical_features] = scaler.fit_transform(final_df[numerical_features])

# Verify scaled features
print(final_df[numerical_features].head())

   age_first_funding_year  age_last_funding_year  funding_rounds_df1  \
0                0.008817              -0.311150            0.492840
1                1.155263               2.046134            1.212245
2               -0.475953              -0.975002           -0.945972
3                0.360399               0.468163            0.492840
4               -0.887593              -0.760795           -0.226566

   funding_total_usd_df1  valuation ($b)
0              -0.132166             0.0
1               0.077539             0.0
2              -0.120420             0.0
3               0.077011             0.0
4              -0.127283             0.0

In [63]:
from sklearn.model_selection import train_test_split

# Define features and target variable
X = final_df.drop(columns=['status_encoded'])
y = final_df['status_encoded']

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Confirm shapes
print("Training set shape:", X_train.shape)
print("Test set shape:", X_test.shape)

Training set shape: (739, 58)
Test set shape: (185, 58)

In [64]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize the model
rf_model = RandomForestClassifier(random_state=42)

# Train the model
rf_model.fit(X_train, y_train)

# Predict on the test set
y_pred = rf_model.predict(X_test)

In [65]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.745945945945946

Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.91      0.83       128
           1       0.65      0.39      0.48        57

    accuracy                           0.75       185
   macro avg       0.71      0.65      0.66       185
weighted avg       0.73      0.75      0.72       185


Confusion Matrix:
 [[116  12]
 [ 35  22]]

In [66]:
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

# Apply SMOTE to balance the training set
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# Train the model with the resampled data
rf_classifier_smote = RandomForestClassifier(random_state=42)
rf_classifier_smote.fit(X_train_resampled, y_train_resampled)

# Make predictions on the test set
y_pred_smote = rf_classifier_smote.predict(X_test)

In [67]:
# Evaluate the model
accuracy_smote = accuracy_score(y_test, y_pred_smote)
classification_report_smote = classification_report(y_test, y_pred_smote)
confusion_matrix_smote = confusion_matrix(y_test, y_pred_smote)

In [68]:
# Display the results
print(f"Accuracy after SMOTE: {accuracy_smote}")
print("\nClassification Report after SMOTE:")
print(classification_report_smote)
print("\nConfusion Matrix after SMOTE:")
print(confusion_matrix_smote)

Accuracy after SMOTE: 0.6972972972972973

Classification Report after SMOTE:
              precision    recall  f1-score   support

           0       0.79      0.77      0.78       128
           1       0.51      0.53      0.52        57

    accuracy                           0.70       185
   macro avg       0.65      0.65      0.65       185
weighted avg       0.70      0.70      0.70       185


Confusion Matrix after SMOTE:
[[99 29]
 [27 30]]

In [71]:
# Import necessary libraries
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Split data into training and test sets (repeat if needed)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Apply SMOTE to balance the training data
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

# Define parameter grid for RandomizedSearchCV
param_dist = {
    'n_estimators': [50, 100, 200, 300],
    'max_depth': [None, 10, 20, 30, 40],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2']
}

# Initialize Random Forest Classifier and RandomizedSearchCV
rf = RandomForestClassifier(random_state=42)
random_search = RandomizedSearchCV(
    rf, param_distributions=param_dist, 
    n_iter=50, cv=3, scoring='accuracy', n_jobs=-1, random_state=42
)

# Fit the model with tuned parameters
random_search.fit(X_train_res, y_train_res)

# Best model from RandomizedSearchCV
best_rf = random_search.best_estimator_
print("Best parameters found: ", random_search.best_params_)

# Evaluate on the test set
y_pred_best_rf = best_rf.predict(X_test)
print("Accuracy after tuning:", accuracy_score(y_test, y_pred_best_rf))
print("Classification Report after tuning:")
print(classification_report(y_test, y_pred_best_rf))
print("Confusion Matrix after tuning:")
print(confusion_matrix(y_test, y_pred_best_rf))

Best parameters found:  {'n_estimators': 100, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2', 'max_depth': 40}
Accuracy after tuning: 0.6864864864864865
Classification Report after tuning:
              precision    recall  f1-score   support

           0       0.77      0.79      0.78       128
           1       0.49      0.46      0.47        57

    accuracy                           0.69       185
   macro avg       0.63      0.62      0.62       185
weighted avg       0.68      0.69      0.68       185

Confusion Matrix after tuning:
[[101  27]
 [ 31  26]]

In [75]:
import joblib
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Ensure feature names are captured as a list
feature_names = list(X_train.columns)  # Convert columns to a list explicitly

# Define and fit scaler and encoder on the training data
scaler = StandardScaler().fit(X_train)
encoder = LabelEncoder().fit(y_train)

# Save all objects in a dictionary
model_artifacts = {
    'model': best_rf,       # Trained RandomForest model
    'scaler': scaler,       # Scaler fitted to X_train
    'encoder': encoder,     # Encoder fitted to y_train
    'feature_names': feature_names  # List of feature names
}

# Save using joblib
joblib_file = "model_with_scaler_and_encoder.pkl"
joblib.dump(model_artifacts, joblib_file)

print(f"Model and preprocessing objects saved to {joblib_file}")

Model and preprocessing objects saved to model_with_scaler_and_encoder.pkl